version: "3.3"
services:
  db:
    image: postgres
    container_name: pg-db
    env_file:
      - config/.env
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
  web:
    image: iva1nn/ruby-app:latest
    container_name: ruby-app
    command:
      - bash -c ./entrypoint.sh
    ports:
      - "3000:3000"
    depends_on:
      - db
