version: "3.3"
services:
  db:
    image: postgres
    container_name: pg-db
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - APP_DB_USER=kitten
      - APP_DB_PASS=qwerty123
      - APP_DB_NAME=kitten_store
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
  web:
    image: iva1nn/ruby-app:latest
    container_name: ruby-app
    command:
      - bash -c ./entrypoint.sh
    ports:
      - "3000:3000"
    depends_on:
      - db