version: "3.3"
services:
  db:
    image: postgres
    environment:    
      - POSTGRES_PASSWORD=password
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  web:
    image: kittens-store:lts
    build: .
    command: 
      bash -c "rm -f tmp/pids/server.pid &&
      bundle exec rake db:create &&
      bundle exec rake db:migrate &&
      bundle exec rake db:seed &&
      bundle exec rackup --port 3000 --host '0.0.0.0'"
    volumes:
      - .:/kittens
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/kitten_store