pg: &pg
  adapter: postgresql
  encoding: unicode
  database: kitten_store
  username: kitten
  password: qwerty123
  host: db
  pool: 30


development:
  <<: *pg

test:
  <<: *pg

production:
  <<: *pg