# PostgreSQL StatefulSet ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-db-config
  labels:
    app: postgresql-db
data:
  POSTGRES_DB: appstore
  POSTGRES_USER: mykittens
  POSTGRES_PASSWORD: admin123
  PGDATA: /data/pgdata