apiVersion: batch/v1
kind: Job
metadata:
  namespace: sample
  name: setup
spec:
  template:
    metadata:
      name: setup
    spec:
      containers:
      - name: setup
        image: iva1nn/kitten-store:latest
        imagePullPolicy: Always
        command: ["/bin/sh"]
        args: ["-c", "bundle install && bundle exec rake db:create && bundle exec rake db:migrate && bundle exec rake db:seed"]
        envFrom:
        - configMapRef:
            name: rails-config
      restartPolicy: Never